version: '3.8'
services:
 mysql:
  image: mysql
  #mbind: Operation not permittedの回避の為に追加
  cap_add:
    - SYS_NICE
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: mysql_db
  ports:
   - '3306:3306'
  volumes:
   - my_volume:/var/lib/mysql　
 app:
  image: express
  build:
    context: keijiban
    dockerfile: ./Dockerfile
  ports:
    - 3000:3000
  volumes:
    - ./keijiban:/usr/src/app
  working_dir: /usr/src/app
volumes: 
  my_volume: